version: "2"
services:
  imdbpy:
    image: guruparvesh/imdbpy
    ports:
      - "5001:5000"
  frontend:
    image: guruparvesh/react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5001 
    depends_on:
      - imdbpy
  nginx:
    image: guruparvesh/openresty
    ports:
      - "8080:8080"
    volumes:
      - ./openresty.conf:/root/usr/local/openresty/nginx/conf/nginx.conf:ro
