version: '2'
services:
  imdbpy:
    image: guruparvesh/imdbpy
    container_name: imdbpy
    restart: always
    expose:
     - 5000
  frontend:
    image: guruparvesh/react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5001 
    depends_on:
      - imdbpy
  openresty:
    image: guruparvesh/openresty
    container_name: openresty
    restart: always
    ports: 
     - 8080:8080
