name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push-docker:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Change to directory with Dockerfile
      run: cd ./imdbpy/
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: guruparvesh/imdbpy
        registry: docker.io
        dockerfile: imdbpy-src/imdbpy/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
